# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import books_pb2 as books__pb2


class BooksRequestStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBookById = channel.unary_unary(
                '/books.BooksRequest/GetBookById',
                request_serializer=books__pb2.BooksRequestById.SerializeToString,
                response_deserializer=books__pb2.Books.FromString,
                )


class BooksRequestServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBookById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BooksRequestServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBookById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBookById,
                    request_deserializer=books__pb2.BooksRequestById.FromString,
                    response_serializer=books__pb2.Books.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'books.BooksRequest', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BooksRequest(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBookById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/books.BooksRequest/GetBookById',
            books__pb2.BooksRequestById.SerializeToString,
            books__pb2.Books.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
