# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: socials.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsocials.proto\x12\x05\x62ooks\"4\n\x07Socials\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07twitter\x18\x03 \x01(\t\" \n\x12SocialsRequestById\x12\n\n\x02id\x18\x01 \x01(\x05\x32N\n\x0eSocialsRequest\x12<\n\rGetSocialById\x12\x19.books.SocialsRequestById\x1a\x0e.books.Socials\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'socials_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SOCIALS._serialized_start=24
  _SOCIALS._serialized_end=76
  _SOCIALSREQUESTBYID._serialized_start=78
  _SOCIALSREQUESTBYID._serialized_end=110
  _SOCIALSREQUEST._serialized_start=112
  _SOCIALSREQUEST._serialized_end=190
# @@protoc_insertion_point(module_scope)
