# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import socials_pb2 as socials__pb2


class SocialsRequestStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSocialById = channel.unary_unary(
                '/books.SocialsRequest/GetSocialById',
                request_serializer=socials__pb2.SocialsRequestById.SerializeToString,
                response_deserializer=socials__pb2.Socials.FromString,
                )


class SocialsRequestServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSocialById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SocialsRequestServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSocialById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSocialById,
                    request_deserializer=socials__pb2.SocialsRequestById.FromString,
                    response_serializer=socials__pb2.Socials.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'books.SocialsRequest', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SocialsRequest(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSocialById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/books.SocialsRequest/GetSocialById',
            socials__pb2.SocialsRequestById.SerializeToString,
            socials__pb2.Socials.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
